---

- hosts: new
  become: true
  pre_tasks:
  - name: Update Repository
    package:
      update_cache: yes

  - name: Upgrade Distro (Debian - Ubuntu)
    package:
      upgrade: dist
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install Git > Curl > Wget > Net-tools > Htop > Tmux
    apt:
      pkg:
        - git
        - curl
        - wget
        - net-tools
        - htop
        - tmux
      state: latest

  - name: Backup file before Copying
    tags: backup
    copy:
      src: /home/freaky/.bashrc
      remote_src: yes
      dest: /home/freaky/.bashrc.bak
      owner: freaky
      group: freaky
      mode: 0644

  - name: Clone from github 
    git:
      repo: https://github.com/Freaky2112/Aliases.git
      dest: /home/freaky/Aliases 
  
  - name: Copy bashrc file for color prompt and aliases
    tags: copy
    copy:
      remote_src: yes
      src: /home/freaky/Aliases/.bashrc
      dest: /home/freaky/.bashrc
      owner: freaky
      gourp: freaky
      mode: 0644

  - name: Copy bashrc file for color prompt and aliases
    tags: copy
    copy:
      src: /home/freaky/Aliases/.tmux.conf
      remote_src: yes
      dest: /home/freaky/.tmux.conf
      owner: freaky
      gourp: freaky
      mode: 0644
      
