---

- hosts: all
  become: true
  pre_tasks:
  - name: Update Repository
    tags: always
    package:
      update_cache: yes
    changed_when: false

- tasks:
    - name: Install Package on Fresh Install
      package:
        - name: 
            - git
            - curl
            - wget
            - tmux
            - htop
      state: latest
      update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]
