---

- hosts: new
  become: true
  pre_tasks:
  - name: Update Repository
    tags: always
    package:
      update_cache: yes
    changed_when: false

  - name: Install Git > Curl > Wget > Net-tools > Htop > Tmux
    apt:
      pkg:
        - git
        - curl
        - wget
        - net-tools
        - htop
        - tmux
      state: latest

  - name: Backup file before Copying
    tags: backup
    copy:
      src: /home/freaky/.bashrc
      remote_src: yes
      dest: /home/freaky/.bashrc.bak
  
  - name: Copy bashrc file for color prompt and aliases
    tags: copy
    copy:
      src: .bashrc
      dest: /home/freaky/.bashrc
      owner: freaky
      gourp: freaky
      mode: 0644
      