---

- hosts: all
  become: true
  vars:
    ansible_python_interpreter: auto
  tasks:

  - name: Update Repository
    apt:
      update_cache: yes

  - name: install Package on Fresh Install
    apt:
      name: git
      state: latest
