---

- hosts: all
  become: true
  pre_tasks:
  - name: Update Repository
    tags: always
    package:
      update_cache: yes
    changed_when: false

  - name: Start and Enable Service
    tags: enable
    service:
      name: ssh
      state: started
      enable: yes

