---

- hosts: all
  become: true
  pre_tasks:
  - name: Update Repository
    tags: always
    package:
      update_cache: yes

  - name: Upgrade Distro (Debian - Ubuntu)
    package:
      upgrade: dist 
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Upgrade Distro (Centos - RedHat)
    package:
      update_only: yes
    when: ansible_distribution in ["Centos", "RedHat", "Fedora"]

  - name: Copy Files....
    tags: copy
    copy:
      src: filename
      dest: /var/www/html/filename
      owner: root
      group: root
      mode: 0644

  - name: Start and Enable Service
    tags: enable
    service:
      name: service_name
      state: started
      enable: yes

  - name: 
    tags: mod 
    lineinfile:
      path: /path of the file/file
      regexp: '^begining of the line'
      line: text for the new line
