---

- hosts: all
  become: true
  pre_tasks:
  - name: Update Repository
    tags: always
    package:
      update_cache: yes
    changed_when: false

  - name: Backup file before Copying
    tags: backup
    copy:
      src: /home/freaky/.bashrc
      dest: /home/freaky/.bashrc.bak
   
  - name: Copy bashrc file for color prompt and aliases
    tags: copy
    copy:
      src: .bashrc
      dest: /home/freaky/.bashrc    
      owner: freaky
      group: freaky
      mode: 0644
