---

- hosts: Test
  become: true
  pre_tasks:
  - name: Update Repository
    tags: always
    package:
      update_cache: yes

  - name: Ensure PermitRootLogin no set to no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRoot'
      line: PermitRootLogin no 

  - name: Ensure PubkeyAuthentication set to yes
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PubkeyAuth'
      line: PubkeyAuthentication yes

  - name: Ensure PasswordAuthentication set to no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuth'
      line: PasswordAuthentication no

  - name: Ensure PermitEmptyPasswords set to no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitEmpty'
      line: PermitEmptyPasswords no
