---

- hosts: all
  become: true
  pre_tasks:
  - name: Update Repository
    package:
      update_cache: yes

  - name: Upgrade Distro (Debian - Ubuntu)
    package:
      upgrade: dist 
    when: ansible_distribution in ["Debian", "Ubuntu"]
